# Generated by Django 6.0 on 2026-01-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
