# Generated by Django 6.0 on 2026-01-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_alter_ventagarage_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventagarage',
            name='rutacertificado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='descripcion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
