# Generated by Django 6.0 on 2026-01-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0008_productolaboral_rutaproductolaboral'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosacademicos',
            name='rutaproductoacademico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
