# Generated by Django 6.0 on 2026-01-08 02:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0015_alter_cursorealizado_rutacertificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursorealizado',
            name='rutacertificado',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='certificado'),
        ),
    ]
