# Generated by Django 6.0 on 2026-01-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0016_alter_cursorealizado_rutacertificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='titulodescripcion',
            field=models.CharField(default='Desarrollador web', max_length=200),
            preserve_default=False,
        ),
    ]
