# Generated by Django 6.0 on 2026-01-04 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_ventagarage_rutacertificado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventagarage',
            old_name='rutacertificado',
            new_name='rutaproducto',
        ),
    ]
