# Generated by Django 6.0 on 2026-01-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_rename_rutacertificado_ventagarage_rutaproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productolaboral',
            name='rutaproductolaboral',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
