# Generated by Django 6.0 on 2026-01-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0010_alter_cursorealizado_rutacertificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='fotodeperfil',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
