# Generated by Django 6.0 on 2026-01-08 02:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0014_alter_cursorealizado_rutacertificado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursorealizado',
            name='rutacertificado',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
